[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/rcklipper/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    127.0.0.1
    192.168.0.0/16
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz
    
[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager fluidd]
path: /home/rcklipper/fluidd
repo: fluidd-core/fluidd
channel: stable
type: web

[update_manager fluidd-config]
managed_services: klipper
origin: https://github.com/fluidd-core/fluidd-config.git
path: /home/rcklipper/fluidd-config
primary_branch: master
type: git_repo

[update_manager z_calibration]
type: git_repo
path: /home/rcklipper/klipper_z_calibration
origin: https://github.com/protoloft/klipper_z_calibration.git
managed_services: klipper

[update_manager klipper_auto_speed]
type: git_repo
path: ~/klipper_auto_speed
origin: https://github.com/anonoei/klipper_auto_speed.git
primary_branch: main
install_script: install.sh
managed_services: klipper

# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[include moonraker-obico-update.cfg]
